server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
#  queue: pedidosQueue
#  exchange: logisticaExchange
#  routingkey: pedidosRoutingKey
  exchange: logistica.exchange

# Configurações para serviços externos
services:
  usuario:
    url: "http://localhost:8080"
  rastreamento:
    url: "http://localhost:8082"
  osrm:
    base-url: "http://router.project-osrm.org"

logging:
  level:
    com.logistica.pedidos: DEBUG
    org.springframework.amqp: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
