server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


rabbitmq:
  exchange: logistica.exchange

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.logistica.notificacoes: DEBUG
    org.springframework.amqp: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
